name: avaliacao_stands
description: Aplicação para avaliar stands e oficinas

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.0
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3  # Para gerar hashes
  universal_html: ^2.2.4  # Para acessar APIs do navegador

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true